### ISSUE TITLE
(ERROR/3) Undefined substitution referenced

### ISSUE THREAD

**Issue by dforsi** [jedie/python-creole#26]
Hello,

using html2rest to convert the attached [test.html.txt](https://github.com/jedie/python-creole/files/105711/test.html.txt) results in a file containing a single line indented with 2 spaces:
`title  some text\\|test|.. |test| image:: test.jpg`
and when I convert that file with rst2html and other converters from Debian's docutils 0.12+dfsg-1 I get:
`test.rst:1: (ERROR/3) Undefined substitution referenced: "test".`

thank you,
Daniele

**Comment by jedie** [comment]
Thanks for reporting.

Any idea to fix this?

**Comment by dforsi** [comment]
I'm learning reStructuredText but it seems to me that explicit markup blocks ".. " must be at the beginning of a line after the indent if any, so as has an hack, having `_get_block_data()` insert `"\n"` before the content makes the converter happy:
``` diff
--- creole/emitter/html2rest_emitter.py.orig	2016-01-28 15:15:56.528594017 +0100
+++ creole/emitter/html2rest_emitter.py	2016-01-28 15:15:58.280546127 +0100
@@ -53,7 +53,7 @@
         """
         content = "\n".join(self._substitution_data)
         self._substitution_data = []
-        return content
+        return "\n" + content
 
     #--------------------------------------------------------------------------
 ```
This fixes the original "Undefined substitution referenced" error but another error is shown
```
test.rst:2: (WARNING/2) Block quote ends without a blank line; unexpected unindent.
```
this is caused in my specific case because the contents of the HTML title is indented but I think it's a different issue, unless the code that handles the title (I can't find it) does something that confuses other code.

**Comment by jedie** [comment]
Great!

Can you create a pull request with a test case for this, please?

**Comment by jedie** [comment]
It's merged with https://github.com/jedie/python-creole/commit/06bd422b92401f2feb6b4b9fcdfd9d6246068513 so i will close this.

Please reopen, if something wrong ;)
