### ISSUE TITLE
I have written a mild extension to allow image size

### ISSUE THREAD

**Issue by JohnAD** [jedie/python-creole#29]
I've written almost trivial change on my fork of python-creole and would be happy to send a pull request to the repo.

I currently use creole for allowing users to create text content on a variety of my websites. The problem I've encounted is that creole's image support is not properly complete. It allows for people to add inline images, for example:

```
{{my_image.png | My Image}}
```

which in turn, renders the html:

```
<img src="my_image.png" title="My Image" alt="My Image" />
```

But when the web page is requested, it is, by default, forcing the web browser to load (or start loading) any images before it can stably render the web page. That is because the rendering engine does not know how _big_ the picture should be yet.

If there are one or two images on a small page; that is not a big deal. But for dozens of pictures on a large page; or where the images are  being pulled from another domain, this can wreak havoc on the user viewing the page. The page will "bounce around" while loading the pictures. It can get really bad on a mobile device.

How can this be solved? Well, I could write a macro of some kind. A `<<sized_image ...>>` of some kind. But there are two non-technical problems with that:

1. Creole's philosophy is that "there should  only be one way of doing something". I've now created two ways of doing the same thing: display an image.
2. Macro's are generally meant for exceptional cases. Myself, I use the `<<pre>>` and `<<code>>` macros already. I've also written an `<<anchor>>` macro for adding link anchors. But those are rare use items. Adding images is far more common.

My fix?

I added an option to creole2html:

```
creole2html(text, allow_img_size=True)
```

Which allows another pipe symbol followed by comma-separated width and height:

```
{{my_image.png | My Image | 160, 90 }}
```
which renders:

```
<img src="my_image.png" title="My Image" alt="My Image" width="160" height="90" />
```

By default, `allow_img_size==False` since, by default, the library should process creole sticking to the pure specfication.

Interested in this option? If so, let me know. I'll add it to the documentation, add a test case, and then send a pull request.

**Comment by JohnAD** [comment]
I should point out that even when `allow_img_size=True`, the image size is still optional in the creole text. If the second bar is missing or if there is not a width/height after the bar, then the `{{...}}` content is rendered the traditional way. Any kind of error falls back to the traditional method as it is wrapped in a `try ... except` structure.

**Comment by jedie** [comment]
Any contribution is welcome ;) But updated tests are needed.

I think a **allow_img_size=True** is not needed: If the image tag contains valid pixel information, then use it.

What's about this syntax:

`{{my_image.png | My Image | 160x90 }}`

I think that makes the meaning clearer, isn't it?

**Comment by jedie** [comment]
Is implemented and released, see: https://github.com/jedie/python-creole/pull/30
