### ISSUE TITLE
Provide `tox.ini` for easier local testing

### ISSUE THREAD

**Issue by jugmac00** [jedie/python-creole#34]
With tox / https://tox.readthedocs.io/en/latest/ it is easier to test multiple python versions locally.

A basic `tox.ini` could look like this:

```
[tox]
envlist =
    py27,
    py36,
    py37,
    py38

[testenv]
deps =
    nose
commands =
    python setup.py nosetests
```

This currently fails as `docutils` is not installed:

```
❯ tox -e=py36
GLOB sdist-make: /home/jugmac00/Projects/python-creole/setup.py
ERROR: invocation failed (exit code 1), logfile: /home/jugmac00/Projects/python-creole/.tox/log/GLOB-0.log
======================================================= log start =======================================================
Test creole2rest and raise an error, if rendering failed...
Traceback (most recent call last):
  File "/home/jugmac00/Projects/python-creole/creole/rest_tools/pypi_rest2html.py", line 26, in <module>
    import docutils
ModuleNotFoundError: No module named 'docutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    long_description = get_long_description(PACKAGE_ROOT)
  File "/home/jugmac00/Projects/python-creole/creole/setup_utils.py", line 121, in get_long_description
    from creole.rest_tools.pypi_rest2html import pypi_rest2html
  File "/home/jugmac00/Projects/python-creole/creole/rest_tools/pypi_rest2html.py", line 36, in <module>
    raise DocutilsImportError(msg)
creole.exceptions.DocutilsImportError: No module named 'docutils' - You can't use rest2html! Please install: http://pypi.python.org/pypi/docutils
```

I guess  both `docutils` and `pygments` should be listed in the `setup.py` as `extra_require`

**Comment by jugmac00** [comment]
This seems to be the problem... I can't create a package locally, and so also tox fails.

```
python setup.py sdist
Test creole2rest and raise an error, if rendering failed...
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    long_description = get_long_description(PACKAGE_ROOT)
  File "/home/jugmac00/Tests/test-creole/python-creole/creole/setup_utils.py", line 121, in get_long_description
    from creole.rest_tools.pypi_rest2html import pypi_rest2html
  File "/home/jugmac00/Tests/test-creole/python-creole/creole/rest_tools/pypi_rest2html.py", line 25, in <module>
    import docutils
ModuleNotFoundError: No module named 'docutils'
```

I wonder how you created the past packages for pypi.

**Comment by jugmac00** [comment]
**Update**

After some more investigation and some lengthy explanation from a helping hand, it looks like it is impossible to use `tox` with the current `setup.py`, as `setup.py` is dependent from `creole` itself and its dependencies - which aren't present when `tox` tries to build the package.

I just noticed that you began modernizing the project and you will introduce `poetry`.

So I will postpone the possible introduction of tox after the packaging issue is solved - provided you would like to have `tox` introduced. It makes testing for multiple python versions so much easier.

**Comment by jugmac00** [comment]
**Update**

Based on @jedie 's branch `poetry` I was able to make `tox` working - it is just a **work in progress** pr, but looks good for me so far - see #35

**Comment by jedie** [comment]
It's done with #36 

Now you can run this:
```
# Run pytest via tox with all environments:
~/python-crole$ make tox

# Run pytest via tox with one Python version:
~/python-crole$ make tox-py38
~/python-crole$ make tox-py37
~/python-crole$ make tox-py36
```

See: https://github.com/jedie/python-creole/blob/master/README.creole#unittests

**Comment by jedie** [comment]
It's release as v1.4.0

**Comment by jugmac00** [comment]
Thank you so much!

Tox works now like a charm.

When running it the first time, I found a small regression see #37
