### ISSUE TITLE
Don't copy README.creole to $PWD

### ISSUE THREAD

**Issue by ekbfh** [jedie/python-creole#40]
Hello!
I have a work folder cloned from git and `virtualenv` in `./bin/`
I have `./bin` in `.gitignore`, just in case.

I installing pip packets like `./bin/pip install python-creole==1.3.2` and getting a `README.creole` in my git folder. 
I wasn't glad when found dirty git.

```
./bin/pip uninstall python-creole
Found existing installation: python-creole 1.3.2
Uninstalling python-creole-1.3.2:
  Would remove:
    /tmp/test/test5/README.creole
    /tmp/test/test5/bin/creole2html
    /tmp/test/test5/bin/html2creole
    /tmp/test/test5/bin/html2rest
    /tmp/test/test5/bin/html2textile
    /tmp/test/test5/lib/python3.6/site-packages/creole/*
    /tmp/test/test5/lib/python3.6/site-packages/python_creole-1.3.2.dist-info/*

```
Please, consider not to copy this file anywhere

**Comment by jedie** [comment]
The new v1.4.x used portry and i think this problem is away.

Please can you test with v1.4.2 ?

**Comment by ekbfh** [comment]
Yep, it's no problem at 1.4.2, but i use python2, so can't use 1.4.x right now.
Thank you!
