### ISSUE TITLE
docutils dependency causing conflict with botocore

### ISSUE THREAD

**Issue by rslinckx** [jedie/python-creole#44]
Since the refactoring work to move to poetry and pyproject, a dependency on docutils>=0.16 has been added to the project dependencies.

botocore seems to also have a dependency on docutils >=0.15, <0.16, which makes both packages not installable at the same time.

On the last version before the refactor (1.3.2 i think) there were no documented dependencies in setup.py

Questions:
- Is the docutils really a dependency to run the code, or just a dev-dependency ?
- Can the requirement be lowered to >=0.15 ?
- Otherwise can it be marked as an optional dependency ?
- Unrelated, but I also noticed that poetry-publish is marked as dependency, shouldn't this really be a dev dependency ?

Thanks a lot !

**Comment by jedie** [comment]
Whops. Good points. Think the easiest way to fix this is to move "docutils" and "poetry-publish" as dev-dependency.

**Comment by rslinckx** [comment]
Great !

Is there any chance you could cut a release with the change ?

**Comment by jedie** [comment]
Yes, I can release soon.

**Comment by jedie** [comment]
It's released as v1.4.4
